### ISSUE TITLE
Data Science Bootcamp Prep: Labs Refresh Issue

### ISSUE THREAD

**Issue by nitdip** [learn-co-curriculum/single-variable-regression-lab#6]
Hello,

Whenever I'm working on the labs they automatically refresh periodically. Sometimes it's seconds in between other times it could be minutes. Is there a way for me to fix this?

I'm connected to github per my account settings and I've disconnected and reconnected, but I still have the issue.

**Comment by L-Lewis** [comment]
I have the same issue - none of my code saves. Did you find a solution to this?

**Comment by nitdip** [comment]
The work around would be to fork the the lessons locally.
