### ISSUE TITLE
Error running pre-written plotly code at end of lesson

### ISSUE THREAD

**Issue by L-Lewis** [learn-co-curriculum/single-variable-regression-lab#8]
When attempting to run the pre-written code `plot([comedy_show_trace, trace_show_line])` on Chrome 70.0.3538.110 on Windows 10 I get the following error, and am unable to produce the graph with plotly:

ValueErrorTraceback (most recent call last)
<ipython-input-99-b26eb014e958> in <module>()
----> 1 plot([comedy_show_trace, trace_show_line])

<ipython-input-84-6698ba7ef0da> in plot(traces)
      1 def plot(traces):
----> 2     plotly.offline.iplot(traces)

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/offline/offline.py in iplot(figure_or_data, show_link, link_text, validate, image, filename, image_width, image_height, config)
    334     config.setdefault('linkText', link_text)
    335 
--> 336     figure = tools.return_figure_from_figure_or_data(figure_or_data, validate)
    337 
    338     # Though it can add quite a bit to the display-bundle size, we include

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/tools.py in return_figure_from_figure_or_data(figure_or_data, validate_figure)
   1467 
   1468         try:
-> 1469             figure = Figure(**figure).to_dict()
   1470         except exceptions.PlotlyError as err:
   1471             raise exceptions.PlotlyError("Invalid 'figure_or_data' argument. "

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/graph_objs/_figure.py in __init__(self, data, layout, frames)
    312                         respective traces in the data attribute
    313         """
--> 314         super(Figure, self).__init__(data, layout, frames)
    315 
    316     def add_area(

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in __init__(self, data, layout_plotly, frames)
    114 
    115         # ### Import traces ###
--> 116         data = self._data_validator.validate_coerce(data)
    117 
    118         # ### Save tuple of trace objects ###

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v)
   1953                         invalid_els.append(v_el)
   1954                     else:
-> 1955                         trace = self.class_map[trace_type](**v_copy)
   1956                         res.append(trace)
   1957                 else:

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/graph_objs/_scatter.py in __init__(self, arg, cliponaxis, connectgaps, customdata, customdatasrc, dx, dy, error_x, error_y, fill, fillcolor, hoverinfo, hoverinfosrc, hoverlabel, hoveron, hovertext, hovertextsrc, ids, idssrc, legendgroup, line, marker, mode, name, opacity, r, rsrc, selected, selectedpoints, showlegend, stream, t, text, textfont, textposition, textpositionsrc, textsrc, tsrc, uid, unselected, visible, x, x0, xaxis, xcalendar, xsrc, y, y0, yaxis, ycalendar, ysrc, **kwargs)
   2131         self.xsrc = xsrc if xsrc is not None else _v
   2132         _v = arg.pop('y', None)
-> 2133         self.y = y if y is not None else _v
   2134         _v = arg.pop('y0', None)
   2135         self.y0 = y0 if y0 is not None else _v

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in __setattr__(self, prop, value)
   2691                 prop in self._validators):
   2692             # Let known properties and private properties through
-> 2693             super(BasePlotlyType, self).__setattr__(prop, value)
   2694         else:
   2695             # Raise error on unknown public properties

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/graph_objs/_scatter.py in y(self, val)
   1409     @y.setter
   1410     def y(self, val):
-> 1411         self['y'] = val
   1412 
   1413     # y0

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in __setitem__(self, prop, value)
   2663             # ### Handle simple property ###
   2664             else:
-> 2665                 self._set_prop(prop, value)
   2666 
   2667         # Handle non-scalar case

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in _set_prop(self, prop, val)
   2893         # ------------
   2894         validator = self._validators.get(prop)
-> 2895         val = validator.validate_coerce(val)
   2896 
   2897         # val is None

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v)
    311             v = to_scalar_or_list(v)
    312         else:
--> 313             self.raise_invalid_val(v)
    314         return v
    315 

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in raise_invalid_val(self, v)
    214             typ=type_str(v),
    215             v=repr(v),
--> 216             valid_clr_desc=self.description()))
    217 
    218     def raise_invalid_elements(self, invalid_els):

ValueError: 
    Invalid value of type 'builtins.dict' received for the 'y' property of scatter
        Received value: {'x': [200, 400, 300, 600], 'y': [400.0, 650.0, 525.0, 900.0]}

    The 'y' property is an array that may be specified as a tuple,
    list, numpy array, or pandas Series

**Comment by ghost** [comment]
I'm running into the same problem on this one.

**Comment by ghost** [comment]
I'm wondering if it has something to do with the y values being floats. Guessing that the y values are in some sort of unsupported data structure, possibly that array thing, that isn't specific enough or compatible with plotly? It may be breaking things in the next lesson as well :(

**Comment by kevinacrystal** [comment]
could it be because trace_show_lines returns the keys "x_values" and "y_values" instead of "x" and 
"y"?
